version: '3.8'

services:
  barbican:
    #image: registry.redhat.io/ubi9/ubi:latest
    image: openstack/mydev:1.0
    container_name: barbican
    environment:
      DEBUGPY_ENABLE_API: false
      DEBUGPY_ENABLE_CMD: false
      DEV_REPO: https://github.com/azkaoru/barbican.git
      DEV_BRANCH: my-feature-branch
      SOFTHSM_USERPIN: userpin123
      SOFTHSM_SOPIN: sopin123
      SOFTHSM_TOKEN_LABEL: token0
      SOFTHSM_SLOT_ID: 0
      SOFTHSM2_CONF: /etc/softhsm2.conf
    command:
      - /bin/bash
      - -c
      - |
        set -x
        useradd -r -s /bin/false barbican || true
        # /var/lib/softhsmの権限がods:odsのため、barbican ユーザーを ods グループに追加
        usermod -aG ods barbican

        #
        # ソースコード取得
        #
        git clone ${DEV_REPO} -b ${DEV_BRANCH} /opt/barbican
        usermod -d /opt/barbican barbican
        cd /opt/barbican
        #
        # Pythonパッケージインストール
        #
        python3.9 -m pip install -r requirements.txt
        python3.9 -m pip install -r test-requirements.txt
        python3.9 -m pip install -e .
        #
        # all tests実行
        #
        # python3.9 -m stestr run 
        # 特定のテストケース実行例
        # python3.9 -m stestr run barbican.tests.cmd.test_barbican_manage.TestBarbicanManage.test_rewrap_pkek 
        #
        # Token初期化
        # 
        softhsm2-util --init-toke --slot $SOFTHSM_SLOT_ID  --label $SOFTHSM_TOKEN_LABEL --so-pin $SOFTHSM_SOPIN --pin $SOFTHSM_USERPIN
        #
        # p11_crypto_plugin設定追加
        #
        cat > /tmp/barbican_p11_config << EOF
        [p11_crypto_plugin]
        library_path = /usr/lib64/pkcs11/libsofthsm2.so
        token_serial_number = $(softhsm2-util --show-slots | grep -m 1 "Serial number:" | sed -e "s/^.*Serial number:\s*//")
        login = ${SOFTHSM_USERPIN}
        mkek_label = 'softhsm_mkek_0'
        mkek_length = 32
        hmac_label = 'softhsm_hmac_0'
        slot_id = $(softhsm2-util --show-slots | grep -m 1 Slot | sed -e "s/^Slot //")
        encryption_mechanism = CKM_AES_CBC
        hmac_key_type = CKK_GENERIC_SECRET
        hmac_keygen_mechanism = CKM_GENERIC_SECRET_KEY_GEN
        hmac_mechanism = CKM_SHA256_HMAC
        key_wrap_mechanism = CKM_AES_KEY_WRAP_PAD
        key_wrap_generate_iv = False
        aes_gcm_generate_iv = true

        [secretstore]
        enabled_secretstore_plugins = store_crypto
        EOF
        cat /tmp/barbican_p11_config >> /etc/barbican/barbican.conf
        #
        # 鍵作成 /var/lib/softhsm/tokensに書き込まれる
        #
        barbican-manage hsm gen_hmac --library-path /usr/lib64/pkcs11/libsofthsm2.so --passphrase ${SOFTHSM_USERPIN} --slot-id $(softhsm2-util --show-slots | grep -m 1 Slot | sed -e "s/^Slot //") --label softhsm_hmac_0
        barbican-manage hsm gen_mkek --library-path /usr/lib64/pkcs11/libsofthsm2.so --passphrase ${SOFTHSM_USERPIN} --slot-id $(softhsm2-util --show-slots | grep -m 1 Slot | sed -e "s/^Slot //") --label softhsm_mkek_0

        chown -R root:ods /var/lib/softhsm
        chmod -R 777 /var/lib/softhsm/tokens/`ls /var/lib/softhsm/tokens`

        useradd -r -s /bin/false barbican || true
        mkdir -p /etc/barbican/vassals /var/log/barbican /var/lib/barbican
        chown -R barbican:barbican /etc/barbican /var/log/barbican /var/lib/barbican /opt/barbican

        # Configure Apache for Keystone
        cat > /etc/httpd/conf.d/wsgi-barbican.conf << 'EOF'
        Listen 9311

        <VirtualHost *:9311>
            LogLevel debug
            ErrorLogFormat "%{cu}t %M"
            ErrorLog /var/log/barbican/barbican.log
            ServerSignature Off
            CustomLog /var/log/barbican/barbican_access.log combined

            WSGIApplicationGroup %{GLOBAL}
            #WSGIDaemonProcess barbican-public processes=1 threads=1 user=barbican group=barbican display-name=%{GROUP} listen-backlog=100 connect-timeout=60 socket-timeout=120
            WSGIDaemonProcess barbican-public processes=1 threads=1 user=barbican group=barbican display-name=%{GROUP} listen-backlog=100 connect-timeout=600 socket-timeout=1200
            WSGIProcessGroup barbican-public
            #WSGIScriptAlias / "/usr/local/lib/python3.9/site-packages/barbican/api/app.wsgi"
            WSGIScriptAlias / "/opt/barbican/barbican/api/app.wsgi"
            WSGIPassAuthorization On

            #<Directory /usr/local/lib/python3.9/site-packages/barbican/api>
            <Directory /opt/barbican/barbican/api>
                #WSGIProcessGroup barbican-public
                #WSGIApplicationGroup %{GLOBAL}
                Require all granted
            </Directory>
        </VirtualHost>

        EOF
        /bin/sh -c "barbican-manage db upgrade" barbican

        # Start Apache
        /usr/sbin/httpd -D FOREGROUND
    volumes:
      - ./config/barbican.conf:/etc/barbican/barbican.conf
      - ./config-dev/api_audit_map.conf:/etc/barbican/api_audit_map.conf
      - ./config-dev/barbican-api-paste.ini:/etc/barbican/barbican-api-paste.ini
      - ./config-dev/gunicorn-config.py:/etc/barbican/gunicorn-config.py
      - ./config-dev/vassals/barbican-api.ini:/etc/barbican/vassals/barbican-api.ini
      - softhsm_tokens_data:/var/lib/softhsm/tokens
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9311 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9311:9311"
      - "5678:5678"
volumes:
  softhsm_tokens_data:
