version: '3.8'
services:
  barbican-rewrap-test:
    image: openstack/mybase:1.0
    container_name: barbican_rewrap_test
    environment:
      SOFTHSM_USERPIN: userpin123
    volumes:
      - softhsm_tokens_data:/var/lib/softhsm/tokens
      - ./config/barbican.conf:/etc/barbican/barbican.conf
    command:
      - /bin/bash
      - -c
      - |
        set -x
        # Configure  for openstackclient
        cat > /etc/barbican/admin-openrc.sh << 'EOF'
        export OS_USERNAME=admin
        export OS_PASSWORD=admin123
        export OS_PROJECT_NAME=admin
        export OS_TENANT_NAME=admin
        export OS_USER_DOMAIN_NAME=Default
        export OS_USER_DOMAIN_ID=default
        export OS_PROJECT_DOMAIN_NAME=Default
        export OS_PROJECT_DOMAIN_ID=default
        export OS_AUTH_URL=http://barbican_keystone:5000/v3
        export OS_IDENTITY_API_VERSION=3
        EOF

        source /etc/barbican/admin-openrc.sh
        #
        # rewrap test
        #
        barbican-manage hsm gen_hmac --library-path /usr/lib64/pkcs11/libsofthsm2.so --passphrase ${SOFTHSM_USERPIN} --slot-id $(softhsm2-util --show-slots | grep -m 1 Slot | sed -e "s/^Slot //") --label softhsm_hmac_1
        barbican-manage hsm gen_mkek --library-path /usr/lib64/pkcs11/libsofthsm2.so --passphrase ${SOFTHSM_USERPIN} --slot-id $(softhsm2-util --show-slots | grep -m 1 Slot | sed -e "s/^Slot //") --label softhsm_mkek_1

        sed 's/softhsm_hmac_0/softhsm_hmac_1/g' /etc/barbican/barbican.conf > /tmp/barbican1.conf
        sed 's/softhsm_mkek_0/softhsm_mkek_1/g' /tmp/barbican1.conf > /tmp/barbican2.conf
        barbican-manage --config-file /tmp/barbican2.conf hsm rewrap_pkek
volumes:
  softhsm_tokens_data:
