version: '3.8'

services:
  keystone:
    image: openstack/mybase:1.0
    container_name: barbican_keystone
    command:
      - /bin/bash
      - -c
      - |
        useradd -r -s /bin/false keystone || true
        mkdir -p /etc/keystone /var/log/keystone /var/lib/keystone
        chown -R keystone:keystone /etc/keystone /var/log/keystone /var/lib/keystone
        
        # Generate Fernet keys
        keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
        #keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
        
        # Configure Apache for Keystone
        cat > /etc/httpd/conf.d/wsgi-keystone.conf << 'EOF'
        Listen 5000
        Listen 35357

        <VirtualHost *:5000>
            WSGIDaemonProcess keystone-public processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
            WSGIProcessGroup keystone-public
            WSGIScriptAlias / /usr/bin/keystone-wsgi-public
            WSGIApplicationGroup %{GLOBAL}
            WSGIPassAuthorization On
            ErrorLogFormat "%{cu}t %M"
            ErrorLog /var/log/keystone/keystone.log
            CustomLog /var/log/keystone/keystone_access.log combined

            <Directory /usr/bin>
                WSGIProcessGroup keystone-public
                WSGIApplicationGroup %{GLOBAL}
                Require all granted
            </Directory>
        </VirtualHost>

        <VirtualHost *:35357>
            WSGIDaemonProcess keystone-admin processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
            WSGIProcessGroup keystone-admin
            WSGIScriptAlias / /usr/bin/keystone-wsgi-admin
            WSGIApplicationGroup %{GLOBAL}
            WSGIPassAuthorization On
            ErrorLogFormat "%{cu}t %M"
            ErrorLog /var/log/keystone/keystone.log
            CustomLog /var/log/keystone/keystone_access.log combined

            <Directory /usr/bin>
                WSGIProcessGroup keystone-admin
                WSGIApplicationGroup %{GLOBAL}
                Require all granted
            </Directory>
        </VirtualHost>

        Alias /identity /usr/bin/keystone-wsgi-public
        <Location /identity>
          SetHandler wsgi-script
          Options +ExecCGI
          WSGIProcessGroup keystone-public
          WSGIApplicationGroup %{GLOBAL}
          WSGIPassAuthorization On
        </Location>
        EOF
        
        # Wait for database to be ready
        
        # Initialize Keystone database
        keystone-manage db_sync
        
        # Bootstrap Keystone
        keystone-manage bootstrap --bootstrap-password admin123 \
          --bootstrap-admin-url http://barbican_keystone:35357/v3/ \
          --bootstrap-internal-url http://barbican_keystone:5000/v3/ \
          --bootstrap-public-url http://barbican_keystone:5000/v3/ \
          --bootstrap-region-id RegionOne

        # Start Apache
        /usr/sbin/httpd -D FOREGROUND
    volumes:
      - ./config/keystone.conf:/etc/keystone/keystone.conf:ro
      - fernet_keys_data:/etc/keyston/fernet-keys
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://barbican_keystone:5000/v3 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "35357:35357"
      - "5000:5000"
  keystone-init:
    image: openstack/mybase:1.0
    container_name: barbican_keystone_init
    restart: "no"
    depends_on:
      keystone:
        condition: service_healthy
    command:
      - /bin/bash
      - -c
      - |
        echo "--- Keystone Start Sucessful ---"
        set -x
        # Configure  for openstackclient
        cat > /etc/keystone/admin-openrc.sh << 'EOF'
        export OS_USERNAME=admin
        export OS_PASSWORD=admin123
        export OS_PROJECT_NAME=admin
        export OS_TENANT_NAME=admin
        export OS_USER_DOMAIN_NAME=Default
        export OS_USER_DOMAIN_ID=default
        export OS_PROJECT_DOMAIN_NAME=Default
        export OS_PROJECT_DOMAIN_ID=default
        export OS_AUTH_URL=http://barbican_keystone:5000/v3
        export OS_IDENTITY_API_VERSION=3
        EOF
          
        source /etc/keystone/admin-openrc.sh
        # create user barbican
        openstack user create --password barbican --domain default barbican
        # create project service
        openstack project create service
        # barbican to admin role
        openstack role add --project service --user barbican admin
        # create creator role
        openstack role create creator
        # barbican to creator role
        openstack role add --project service --user barbican creator
        # create service barbican
        openstack service create --name barbican --description "Key Manager" key-manager
        # create vip endpoint
        openstack endpoint create --region RegionOne key-manager public http://barbican:9311
        openstack endpoint create --region RegionOne key-manager internal http://barbican:9311
        openstack endpoint create --region RegionOne key-manager admin http://barbican:9311
        openstack endpoint list
        echo "--- Keystone Init Sucessful ---"

volumes:
  fernet_keys_data:

